safe: true
markdown: kramdown

title: snipsnipsnip.github.io
author: snipsnipsnip
url_root: http://snipsnipsnip.github.io
repos_url: http://github.com/snipsnipsnip/snipsnipsnip.github.io

enable_google_code_prettify: true
disqus_shortname: ghsgicay6c
google_analytics_tracking_id: UA-31061392-1
