safe: true
markdown: kramdown

title: snipsnipsnip.github.io
author: snipsnipsnip
url_root: http://snipsnipsnip.github.io
repos_url: https://github.com/snipsnipsnip/snipsnipsnip.github.io
atom_feed: http://feeds.feedburner.com/snipsnipsnipgithubio

enable_google_code_prettify: true
disqus_shortname: ghsgicay6c
google_analytics_tracking_id: UA-31061392-1
google_analytics_name: snipsnipsnip.github.io
